routes/web.php
<?php

use App\Http\Controllers\Admin\BannerController;
use App\Http\Controllers\Admin\BrandController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\CmsPageController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\SimpleProductController;
use App\Http\Controllers\Admin\VariantController;
use App\Http\Controllers\Admin\VariantOptionController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['prefix' => 'admin'], function () {
    Route::middleware(['auth'])->group(function () {
        Route::get('dashboard', [DashboardController::class, 'index'])->name('dashboard')->middleware('auth');
        Route::put('categories/{id}/is-active', [CategoryController::class, 'isActive'])->name('categories.isActive');
        Route::resource('categories', CategoryController::class);
        Route::put('brands/{id}/is-active', [BrandController::class, 'isActive'])->name('brands.isActive');
        Route::resource('brands', BrandController::class);
        Route::put('banners/{id}/is-active', [BannerController::class, 'isActive'])->name('banners.isActive');
        Route::resource('banners', BannerController::class);
        Route::resource('cmspages', CmsPageController::class);
        Route::put('cmspages/{id}/is-active', [CmsPageController::class, 'isActive'])->name('cmspages.isActive');
        Route::put('variants/{id}/is-active', [VariantController::class, 'isActive'])->name('variants.isActive');
        Route::resource('variants', VariantController::class);
        Route::put('variantoptions/{id}/is-active', [VariantOptionController::class, 'isActive'])->name('variantoptions.isActive');
        Route::resource('variantoptions', VariantOptionController::class);
        Route::get('products', [ProductController::class, 'index'])->name('products.index');
        Route::resource('simple-product', SimpleProductController::class);
    });
});

app/Models/Variant.php
<?php

namespace App\Models;

use App\Models\BaseModel;
use Illuminate\Database\Eloquent\SoftDeletes;

class Variant extends BaseModel
{
    use SoftDeletes;

    protected $fillable = ['name', 'slug'];

    protected static function boot()
    {
        parent::boot();

        static::created(function ($variant) {

            $variant->slug = $variant->createSlug($variant->name);

            $variant->save();
        });
    }

    public function options()
    {
        return $this->hasMany(VariantOption::class);
    }
}

app/Http/Controllers/Admin/VariantController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\AdminController;
use App\Http\Requests\VariantRequest;
use App\Repositories\VariantRepository;
use Exception;
use Illuminate\Http\Request;

class VariantController extends AdminController
{
    protected $variantRepository;

    public function __construct(VariantRepository $variantRepository)
    {
        $this->variantRepository = $variantRepository;
    }

    public function index(Request $request)
    {
        $data = $this->variantRepository->getAll($request);

        return view('admin.variants.index', compact('data'));
    }

    public function create()
    {
        return view('admin.variants.create');
    }

    public function store(VariantRequest $request)
    {
        $this->variantRepository->create($request);

        return redirect()->to(route('variants.index'))->with(['message' => 'Variant has been added successfully.']);
    }

    public function edit($id)
    {
        $variant = $this->variantRepository->getById($id);

        return view('admin.variants.edit', compact('variant'));
    }

    public function update(VariantRequest $request, $id)
    {
        $this->variantRepository->update($id, $request);

        return redirect()->to(route('variants.index'))->with(['message' => 'Variant has been updated successfully.']);
    }

    public function destroy($id)
    {
        try {
            $this->variantRepository->delete($id);
        } catch (Exception $ex) {
            return response()->json(['message' => $ex->getMessage()], 422);
        }
    }

    public function isActive(VariantRequest $request, $id)
    {
        $this->variantRepository->isActive($id, $request);
    }
}

resources/views/admin/variants/create.blade.php
@extends('layouts.admin.app')
@section('content')

    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Manage Variants</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Home</a></li>
                        <li class="breadcrumb-item"><a href="{{ route('variants.index') }}">Variants</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Add Variant</li>
                    </ol>
                </div>
            </div>
        </div>
    </section>

    <section class="content">
        <div class="card">
            <div class="card-header">
                <h2 class="card-title">Add Variant</h2>

            </div>
            <div class="card-body">
                <div class="pd-20 bg-white border-radius-4 box-shadow mb-30">
                    @include('layouts.partials.admin.errors')
                    <form name="add_form" id="add_form" method="post" action="{{ route('variants.store') }}">
                        @csrf
                        <div class="row">
                            <div class="col-md-12 p-2">
                                <label for="title">Name <span class="text-danger">*</span></label>
                                <input type="text" name="name" class="form-control" value="{{ old('name') }}">
                            </div>
                            <div class="col-md-12 p-2">
                                <button type="submit" id="submit" name="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="card-footer"></div>
        </div>
    </section>

@endsection

@section('jsfooter')
@endsection

resources/views/admin/variants/edit.blade.php
@extends('layouts.admin.app')
@section('content')

    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Manage Variants</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Home</a></li>
                        <li class="breadcrumb-item"><a href="{{ route('variants.index') }}">Variants</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Edit Variant</li>
                    </ol>
                </div>
            </div>
        </div>
    </section>


    <section class="content">
        <div class="card">
            <div class="card-header">
                <h2 class="card-title">Edit Variant</h2>

            </div>
            <div class="card-body">
                <div class="pd-20 bg-white border-radius-4 box-shadow mb-30">
                    @include('layouts.partials.admin.errors')
                    <form name="edit_form" id="edit_form" method="post"
                        action="{{ route('variants.update', $variant->id) }}">
                        @method('PUT')
                        @csrf
                        <div class="row">
                            <div class="col-md-12 p-2">
                                <label for="name">Name <span class="text-danger">*</span></label>
                                <input type="text" name="name" class="form-control"
                                    value="{{ old('name', $variant->name) }}">
                            </div>
                            <div class="col-md-12 p-2">
                                <button type="submit" id="submit" name="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="card-footer"></div>
        </div>
    </section>


@endsection

@section('jsfooter')
@endsection

resources/views/admin/variants/index.blade.php
@extends('layouts.admin.app')
@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Manage Variants</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Home</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Variants</li>
                    </ol>
                </div>
            </div>
        </div>
    </section>

    <section class="content">
        <div class="card">
            <div class="card-header">
                <div class="d-flex justify-content-between">
                    <h2 class="card-title">Variants</h2>
                    <a class="btn btn-outline-primary btn-sm" href="{{ route('variants.create') }}">
                        <i class="fa fa-plus"></i> Add Variant
                    </a>
                </div>
            </div>
            <div class="card-body">
                <div class="pd-20 bg-white border-radius-4 box-shadow mb-30">
                    @include('layouts.partials.admin.message')
                    @if (sizeof($data) > 0)
                        @include('layouts.partials.admin.paging')
                        <table class="table table-hover mt-3">
                            <thead>
                                <tr>
                                    <th>Name</th>
                                    <th style="width: 20%;">Updated On</th>
                                    <th style="width: 22%;">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($data as $row)
                                    <tr>
                                        <td>{{ $row->name }}</td>
                                        <td>{{ Carbon\Carbon::parse($row->updated_at)->format('F j, Y, g:i a') }}</td>
                                        <td>
                                            <div class="d-flex">
                                                <div class="mr-2">
                                                    <form id="variant_status_{{ $row->id }}" action="" method="post">
                                                        @csrf
                                                        @method('PUT')
                                                        <input type="hidden" name="is_active"
                                                            value="{{ $row->is_active ? 'false' : 'true' }}" />
                                                        <button
                                                            class="btn btn-{{ $row->is_active ? 'success' : 'warning' }} btn-sm"
                                                            type="button"
                                                            onclick="javascript: changeStatus({{ $row->id }}, 'variant_status', '{{ route('variants.isActive', $row->id) }}');return false;">
                                                            {{ $row->is_active ? 'Enabled' : 'Disabled' }}
                                                        </button>
                                                    </form>
                                                </div>
                                                <div class="mr-2">
                                                    <a href="{{ route('variants.edit', $row->id) }}"
                                                        class="btn btn-primary btn-sm"><i class="fa fa-edit">
                                                            Edit</i></a>
                                                </div>
                                                <div class="p-0">
                                                    <form id="variant_delete_{{ $row->id }}" action="" method="post">
                                                        @csrf
                                                        @method('DELETE')
                                                        <button class="btn btn-danger btn-sm" type="button"
                                                            onclick="javascript: deleteRecord({{ $row->id }}, 'variant_delete', '{{ route('variants.destroy', $row->id) }}');return false;"><i
                                                                class="fa fa-trash"> Delete</i></button>
                                                    </form>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                        @include('layouts.partials.admin.paging')
                    @else
                        @include('layouts.partials.admin.noinfo')
                    @endif
                </div>
            </div>
            <div class="card-footer"></div>
        </div>
    </section>

@endsection
@section('jsfooter')

@endsection