routes/web.php
<?php

use App\Http\Controllers\Admin\BannerController;
use App\Http\Controllers\Admin\BrandController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\CmsPageController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\SimpleProductController;
use App\Http\Controllers\Admin\VariantController;
use App\Http\Controllers\Admin\VariantOptionController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['prefix' => 'admin'], function () {
    Route::middleware(['auth'])->group(function () {
        Route::get('dashboard', [DashboardController::class, 'index'])->name('dashboard')->middleware('auth');
        Route::put('categories/{id}/is-active', [CategoryController::class, 'isActive'])->name('categories.isActive');
        Route::resource('categories', CategoryController::class);
        Route::put('brands/{id}/is-active', [BrandController::class, 'isActive'])->name('brands.isActive');
        Route::resource('brands', BrandController::class);
        Route::put('banners/{id}/is-active', [BannerController::class, 'isActive'])->name('banners.isActive');
        Route::resource('banners', BannerController::class);
        Route::resource('cmspages', CmsPageController::class);
        Route::put('cmspages/{id}/is-active', [CmsPageController::class, 'isActive'])->name('cmspages.isActive');
        Route::put('variants/{id}/is-active', [VariantController::class, 'isActive'])->name('variants.isActive');
        Route::resource('variants', VariantController::class);
        Route::put('variantoptions/{id}/is-active', [VariantOptionController::class, 'isActive'])->name('variantoptions.isActive');
        Route::resource('variantoptions', VariantOptionController::class);
        Route::get('products', [ProductController::class, 'index'])->name('products.index');
        Route::resource('simple-product', SimpleProductController::class);
    });
});

app/Models/Brand.php
<?php

namespace App\Models;

use App\Models\BaseModel;
use Illuminate\Database\Eloquent\SoftDeletes;

class Brand extends BaseModel
{
    use SoftDeletes;

    protected static function boot()
    {
        parent::boot();

        static::created(function ($brand) {

            $brand->slug = $brand->createSlug($brand->name);

            $brand->save();
        });
    }
}

app/Http/Controllers/Admin/BrandController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\AdminController;
use App\Http\Requests\BrandRequest;
use App\Repositories\BrandRepository;
use Exception;
use Illuminate\Http\Request;

class BrandController extends AdminController
{
    protected $brandRepository;

    public function __construct(BrandRepository $brandRepository)
    {
        $this->brandRepository = $brandRepository;
    }

    public function index(Request $request)
    {
        $data = $this->brandRepository->getAll($request);

        return view('admin.brands.index', compact('data'));
    }

    public function create()
    {
        return view('admin.brands.create');
    }

    public function store(BrandRequest $request)
    {
        $this->brandRepository->create($request);

        return redirect()->to(route('brands.index'))->with(['message' => 'Brand has been added successfully.']);
    }

    public function edit($id)
    {
        $brand = $this->brandRepository->getById($id);

        return view('admin.brands.edit', compact('brand'));
    }

    public function update(BrandRequest $request, $id)
    {
        $this->brandRepository->update($id, $request);

        return redirect()->to(route('brands.index'))->with(['message' => 'Brand has been updated successfully.']);
    }

    public function destroy($id)
    {
        try {
            $this->brandRepository->delete($id);
        } catch (Exception $ex) {
            return response()->json(['message' => $ex->getMessage()], 422);
        }
    }

    public function isActive(BrandRequest $request, $id)
    {
        $this->brandRepository->isActive($id, $request);
    }
}

resources/views/admin/brands/create.blade.php
@extends('layouts.admin.app')
@section('content')

    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Manage Brands</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Home</a></li>
                        <li class="breadcrumb-item"><a href="{{ route('brands.index') }}">Brands</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Add Brand</li>
                    </ol>
                </div>
            </div>
        </div>
    </section>

    <section class="content">
        <div class="card">
            <div class="card-header">
                <h2 class="card-title">Add Brand</h2>

            </div>
            <div class="card-body">
                <div class="pd-20 bg-white border-radius-4 box-shadow mb-30">
                    @include('layouts.partials.admin.errors')
                    <form name="add_form" id="add_form" method="post" action="{{ route('brands.store') }}">
                        @csrf
                        <div class="row">
                            <div class="col-md-12 p-2">
                                <label for="title">Name <span class="text-danger">*</span></label>
                                <input type="text" name="name" class="form-control" value="{{ old('name') }}">
                            </div>
                            <div class="col-md-12 p-2">
                                <button type="submit" id="submit" name="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="card-footer"></div>
        </div>
    </section>

@endsection

@section('jsfooter')
@endsection

resources/views/admin/brands/edit.blade.php
@extends('layouts.admin.app')
@section('content')

    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Manage Brands</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Home</a></li>
                        <li class="breadcrumb-item"><a href="{{ route('brands.index') }}">Brands</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Edit Brand</li>
                    </ol>
                </div>
            </div>
        </div>
    </section>


    <section class="content">
        <div class="card">
            <div class="card-header">
                <h2 class="card-title">Edit Brand</h2>

            </div>
            <div class="card-body">
                <div class="pd-20 bg-white border-radius-4 box-shadow mb-30">
                    @include('layouts.partials.admin.errors')
                    <form name="edit_form" id="edit_form" method="post" action="{{ route('brands.update', $brand->id) }}">
                        @method('PUT')
                        @csrf
                        <div class="row">
                            <div class="col-md-12 p-2">
                                <label for="name">Name <span class="text-danger">*</span></label>
                                <input type="text" name="name" class="form-control"
                                    value="{{ old('name', $brand->name) }}">
                            </div>
                            <div class="col-md-12 p-2">
                                <button type="submit" id="submit" name="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="card-footer"></div>
        </div>
    </section>


@endsection

@section('jsfooter')
@endsection

resources/views/admin/brands/index.blade.php
@extends('layouts.admin.app')
@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Manage Brands</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Home</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Brands</li>
                    </ol>
                </div>
            </div>
        </div>
    </section>

    <section class="content">
        <div class="card">
            <div class="card-header">
                <div class="d-flex justify-content-between">
                    <h2 class="card-title">Brands</h2>
                    <a class="btn btn-outline-primary btn-sm" href="{{ route('brands.create') }}">
                        <i class="fa fa-plus"></i> Add Brand
                    </a>
                </div>
            </div>
            <div class="card-body">
                <div class="pd-20 bg-white border-radius-4 box-shadow mb-30">
                    @include('layouts.partials.admin.message')
                    @if (sizeof($data) > 0)
                        @include('layouts.partials.admin.paging')
                        <table class="table table-hover mt-3">
                            <thead>
                                <tr>
                                    <th>Name</th>
                                    <th style="width: 20%;">Updated On</th>
                                    <th style="width: 22%;">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($data as $row)
                                    <tr>
                                        <td>{{ $row->name }}</td>
                                        <td>{{ Carbon\Carbon::parse($row->updated_at)->format('F j, Y, g:i a') }}</td>
                                        <td>
                                            <div class="d-flex">
                                                <div class="mr-2">
                                                    <form id="brand_status_{{ $row->id }}" action="" method="post">
                                                        @csrf
                                                        @method('PUT')
                                                        <input type="hidden" name="is_active"
                                                            value="{{ $row->is_active ? 'false' : 'true' }}" />
                                                        <button
                                                            class="btn btn-{{ $row->is_active ? 'success' : 'warning' }} btn-sm"
                                                            type="button"
                                                            onclick="javascript: changeStatus({{ $row->id }}, 'brand_status', '{{ route('brands.isActive', $row->id) }}');return false;">
                                                            {{ $row->is_active ? 'Enabled' : 'Disabled' }}
                                                        </button>
                                                    </form>
                                                </div>
                                                <div class="mr-2">
                                                    <a href="{{ route('brands.edit', $row->id) }}"
                                                        class="btn btn-primary btn-sm"><i class="fa fa-edit">
                                                            Edit</i></a>
                                                </div>
                                                <div class="p-0">
                                                    <form id="brand_delete_{{ $row->id }}" action="" method="post">
                                                        @csrf
                                                        @method('DELETE')
                                                        <button class="btn btn-danger btn-sm" type="button"
                                                            onclick="javascript: deleteRecord({{ $row->id }}, 'brand_delete', '{{ route('brands.destroy', $row->id) }}');return false;"><i
                                                                class="fa fa-trash"> Delete</i></button>
                                                    </form>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                        @include('layouts.partials.admin.paging')
                    @else
                        @include('layouts.partials.admin.noinfo')
                    @endif
                </div>
            </div>
            <div class="card-footer"></div>
        </div>
    </section>

@endsection
@section('jsfooter')

@endsection