routes/web.php
<?php

use App\Http\Controllers\Admin\BannerController;
use App\Http\Controllers\Admin\BrandController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\CmsPageController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\SimpleProductController;
use App\Http\Controllers\Admin\VariantController;
use App\Http\Controllers\Admin\VariantOptionController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['prefix' => 'admin'], function () {
    Route::middleware(['auth'])->group(function () {
        Route::get('dashboard', [DashboardController::class, 'index'])->name('dashboard')->middleware('auth');
        Route::put('categories/{id}/is-active', [CategoryController::class, 'isActive'])->name('categories.isActive');
        Route::resource('categories', CategoryController::class);
        Route::put('brands/{id}/is-active', [BrandController::class, 'isActive'])->name('brands.isActive');
        Route::resource('brands', BrandController::class);
        Route::put('banners/{id}/is-active', [BannerController::class, 'isActive'])->name('banners.isActive');
        Route::resource('banners', BannerController::class);
        Route::resource('cmspages', CmsPageController::class);
        Route::put('cmspages/{id}/is-active', [CmsPageController::class, 'isActive'])->name('cmspages.isActive');
        Route::put('variants/{id}/is-active', [VariantController::class, 'isActive'])->name('variants.isActive');
        Route::resource('variants', VariantController::class);
        Route::put('variantoptions/{id}/is-active', [VariantOptionController::class, 'isActive'])->name('variantoptions.isActive');
        Route::resource('variantoptions', VariantOptionController::class);
        Route::get('products', [ProductController::class, 'index'])->name('products.index');
        Route::resource('simple-product', SimpleProductController::class);
    });
});

app/Models/Category.php
<?php

namespace App\Models;

use App\Models\BaseModel;
use Illuminate\Database\Eloquent\SoftDeletes;

class Category extends BaseModel
{
    use SoftDeletes;

    protected static function boot()
    {
        parent::boot();

        static::created(function ($category) {

            $category->slug = $category->createSlug($category->name);

            $category->save();
        });
    }

    public function subcategory()
    {
        return $this->hasMany(Category::class, 'parent_id');
    }

    public function parent()
    {
        return $this->belongsTo(Category::class, 'parent_id');
    }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\AdminController;
use App\Http\Requests\CategoryRequest;
use App\Repositories\CategoryRepository;
use Exception;
use Illuminate\Http\Request;

class CategoryController extends AdminController
{
    protected $categoryRepository;

    public function __construct(CategoryRepository $categoryRepository)
    {
        $this->categoryRepository = $categoryRepository;
    }

    public function index(Request $request)
    {
        $data = $this->categoryRepository->getAll($request);

        return view('admin.categories.index', compact('data'));
    }

    public function create()
    {
        $parentCategories = $this->categoryRepository->getAllParentCategories();

        return view('admin.categories.create', compact('parentCategories'));
    }

    public function store(CategoryRequest $request)
    {
        $this->categoryRepository->create($request);

        return redirect()->to(route('categories.index'))->with(['message' => 'Category has been added successfully.']);
    }

    public function edit($id)
    {
        $category = $this->categoryRepository->getById($id);

        $parentCategories = $this->categoryRepository->getAllParentCategories();

        return view('admin.categories.edit', compact('category', 'parentCategories'));
    }

    public function update(CategoryRequest $request, $id)
    {
        $this->categoryRepository->update($id, $request);

        return redirect()->to(route('categories.index'))->with(['message' => 'Category has been updated successfully.']);
    }

    public function destroy($id)
    {
        try {
            $this->categoryRepository->delete($id);
        } catch (Exception $ex) {
            return response()->json(['message' => $ex->getMessage()], 422);
        }
    }

    public function isActive(CategoryRequest $request, $id)
    {
        $this->categoryRepository->isActive($id, $request);
    }
}

resources/views/admin/categories/create.blade.php
@extends('layouts.admin.app')
@section('content')

    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Manage Categories</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Home</a></li>
                        <li class="breadcrumb-item"><a href="{{ route('categories.index') }}">Categories</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Add Category</li>
                    </ol>
                </div>
            </div>
        </div>
    </section>

    <section class="content">
        <div class="card">
            <div class="card-header">
                <h2 class="card-title">Add Category</h2>

            </div>
            <div class="card-body">
                <div class="pd-20 bg-white border-radius-4 box-shadow mb-30">
                    @include('layouts.partials.admin.errors')
                    <form name="add_form" id="add_form" method="post" action="{{ route('categories.store') }}">
                        @csrf
                        <div class="row">
                            <div class="col-md-12 p-2">
                                <label for="parent_id">Category <span class="text-danger">*</span></label>
                                <select name="parent_id" class="form-control">
                                    <option value="0">Root</option>
                                    @foreach ($parentCategories as $item)
                                        <option value="{{ $item->id }}"
                                            {{ $item->id == old('parent_id') ? ' selected' : '' }}>
                                            {{ $item->name }}
                                        </option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="col-md-12 p-2">
                                <label for="title">Name <span class="text-danger">*</span></label>
                                <input type="text" name="name" class="form-control" value="{{ old('name') }}">
                            </div>
                            <div class="col-md-12 p-2">
                                <button type="submit" id="submit" name="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="card-footer"></div>
        </div>
    </section>

@endsection

@section('jsfooter')
@endsection

resources/views/admin/categories/edit.blade.php
@extends('layouts.admin.app')
@section('content')

    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Manage Categories</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Home</a></li>
                        <li class="breadcrumb-item"><a href="{{ route('categories.index') }}">Categories</a></li>
                        <li class="breadcrumb-item active" aria-current="Edit">Edit Category</li>
                    </ol>
                </div>
            </div>
        </div>
    </section>


    <section class="content">
        <div class="card">
            <div class="card-header">
                <h2 class="card-title">Edit Category</h2>

            </div>
            <div class="card-body">
                <div class="pd-20 bg-white border-radius-4 box-shadow mb-30">
                    @include('layouts.partials.admin.errors')
                    <form name="edit_form" id="edit_form" method="post"
                        action="{{ route('categories.update', $category->id) }}">
                        @method('PUT')
                        @csrf
                        <div class="row">
                            <div class="col-md-12 p-2">
                                <label for="parent_id">Category <span class="text-danger">*</span></label>
                                <select name="parent_id" class="form-control">
                                    <option value="0">Root</option>
                                    @foreach ($parentCategories as $item)
                                        <option value="{{ $item->id }}"
                                            {{ $item->id == old('parent_id', $category->parent_id) ? ' selected' : '' }}>
                                            {{ $item->name }}
                                        </option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="col-md-12 p-2">
                                <label for="name">Name <span class="text-danger">*</span></label>
                                <input type="text" name="name" class="form-control"
                                    value="{{ old('name', $category->name) }}">
                            </div>
                            <div class="col-md-12 p-2">
                                <button type="submit" id="submit" name="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="card-footer"></div>
        </div>
    </section>


@endsection

@section('jsfooter')
@endsection

resources/views/admin/categories/index.blade.php
@extends('layouts.admin.app')
@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Manage Categories</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Home</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Categories</li>
                    </ol>
                </div>
            </div>
        </div>
    </section>

    <section class="content">
        <div class="card">
            <div class="card-header">
                <div class="d-flex justify-content-between">
                    <h2 class="card-title">Categories</h2>
                    <a class="btn btn-outline-primary btn-sm" href="{{ route('categories.create') }}">
                        <i class="fa fa-plus"></i> Add Category
                    </a>
                </div>
            </div>
            <div class="card-body">
                <div class="pd-20 bg-white border-radius-4 box-shadow mb-30">
                    @include('layouts.partials.admin.message')
                    @if (sizeof($data) > 0)
                        @include('layouts.partials.admin.paging')
                        <table class="table table-hover mt-3">
                            <thead>
                                <tr>
                                    <th>Category Name</th>
                                    <th>Parent Category</th>
                                    <th style="width: 20%;">Updated On</th>
                                    <th style="width: 22%;">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($data as $row)
                                    <tr>
                                        <td>{{ $row->name }}</td>
                                        <td>{{ $row->parent ? $row->parent->name : 'ROOT' }}</td>
                                        <td>{{ Carbon\Carbon::parse($row->updated_at)->format('F j, Y, g:i a') }}</td>
                                        <td>
                                            <div class="d-flex">
                                                <div class="mr-2">
                                                    <form id="category_status_{{ $row->id }}" action="" method="post">
                                                        @csrf
                                                        @method('PUT')
                                                        <input type="hidden" name="is_active"
                                                            value="{{ $row->is_active ? 'false' : 'true' }}" />
                                                        <button
                                                            class="btn btn-{{ $row->is_active ? 'success' : 'warning' }} btn-sm"
                                                            type="button"
                                                            onclick="javascript: changeStatus({{ $row->id }}, 'category_status', '{{ route('categories.isActive', $row->id) }}');return false;">
                                                            {{ $row->is_active ? 'Enabled' : 'Disabled' }}
                                                        </button>
                                                    </form>
                                                </div>
                                                <div class="mr-2">
                                                    <a href="{{ route('categories.edit', $row->id) }}"
                                                        class="btn btn-primary btn-sm"><i class="fa fa-edit">
                                                            Edit</i></a>
                                                </div>
                                                <div class="p-0">
                                                    <form id="category_delete_{{ $row->id }}" action="" method="post">
                                                        @csrf
                                                        @method('DELETE')
                                                        <button class="btn btn-danger btn-sm" type="button"
                                                            onclick="javascript: deleteRecord({{ $row->id }}, 'category_delete', '{{ route('categories.destroy', $row->id) }}');return false;"><i
                                                                class="fa fa-trash"> Delete</i></button>
                                                    </form>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                        @include('layouts.partials.admin.paging')
                    @else
                        @include('layouts.partials.admin.noinfo')
                    @endif
                </div>
            </div>
            <div class="card-footer"></div>
        </div>
    </section>

@endsection
@section('jsfooter')

@endsection